### ISSUE TITLE
Bug: floats with only `0` as decimal places are converted to integer

### ISSUE THREAD

**Issue by RafaelKr** [shopwareLabs/psh#120]
In the Shopware development template I want to explicitly use the docker image `webdevops/php-apache-dev:8.0`. For this I tried to use the following configuration:
```yaml
const:
  DOCKER_IMAGE_PHP: webdevops/php-apache-dev
  DOCKER_IMAGE_PHP_VERSION: 8.0
```
If I do so, docker will try to pull `webdevops/php-apache-dev:8` (note the missing `.0`) which is not available on dockerhub. I got a workaround by wrapping it in quotes which works fine on Linux:
```yaml
const:
  DOCKER_IMAGE_PHP: webdevops/php-apache-dev
  DOCKER_IMAGE_PHP_VERSION: "8.0"
```

Today we tried to set it up on a MacBook of a colleague, although it's wrapped with quotes it will still convert it to an integer and therefore try to pull that non-existent image tag. We tried to escape them with the following options which all didn't work. They all were put into the `docker-compose.override.yml` literally:
```
\"8.0\"
8\.0
8.0 !!float
```

We also tried it with single quotes (`'8.0'`) which led to the same result as double quotes.

For now we just use `8.1` on macOS which works fine. Is there a solution to this or is this something which has to be adjusted in the psh code?
