### ISSUE TITLE
Template Destinations should be able to be used with placeholders

### ISSUE THREAD

**Issue by JanPietrzyk** [shopwareLabs/psh#30]
Sth. like that should be possible:

```yaml
templates:
  - source: templates/consts.tpl
    destination: app/consts-__ENVIRONMENT__.php
```

and resul in `consts-dev.php` if `__ENVIRONMENT__`'s value is `dev`
