### ISSUE TITLE
Add local placeholders

### ISSUE THREAD

**Issue by JanPietrzyk** [shopwareLabs/psh#49]
Since PSH is now used on multiple different systems by different people it seems to be about time to add some local variable handling and helpers.

```yml
const: [...]
dynamic: [...]
local:
   foo: 
      description: "Set foo to bar or baz" (optional if has default)
      default: "bar" (optional if has description)
      storable: true|false (optional: default true)
```
On first use of a particular environment PSH should ask for these parameters and (optionally) write them to a `.overwrite` file.
