### ISSUE TITLE
Implement .env support

### ISSUE THREAD

**Issue by nlubisch** [shopwareLabs/psh#73]
Implement a way to load environment variables from .env files in a global or environment-specific way.
e.g.
```yaml
dotenv: 
  - .env
  - ./path/to/.env
environments:
  foo:
    dotenv:
      - foo/.env
```
